import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';

// Codex-supported hook events (as of v0.124.0-alpha.3, April 2026).
// PermissionRequest added on top of the original 5 Claude Code events.
const CODEX_SUPPORTED_EVENTS = new Set([
  'SessionStart', 'UserPromptSubmit',
  'PreToolUse', 'PostToolUse', 'PermissionRequest', 'Stop',
]);

export interface CodexHookEntry {
  event: string;
  command: { script: string; timeout_sec?: number };
  matcher?: string;
}

/**
 * Generate source of a Codex-compatibility wrapper for a single Claude Code hook script.
 *
 * What the wrapper translates:
 *   - Exit-code-2 block (Claude Code) → `{permissionDecision:"deny"}` JSON with exit 0 (Codex)
 *   - Strips `additionalContext` from stdout JSON (Codex rejects it)
 *   - Forwards stdin/stdout/stderr transparently for all other cases
 *
 * @param originalScriptPath - Absolute path to the hook .cjs being wrapped.
 */
export function generateHookWrapper(originalScriptPath: string): string {
  // JSON.stringify produces a safe string literal for embedding in generated source.
  const escaped = JSON.stringify(originalScriptPath);
  return `'use strict';
// Codex-compatibility wrapper — auto-generated by HailyKit. Do not edit.
// Wraps: ${path.basename(originalScriptPath)}
const { spawnSync } = require('child_process');

const chunks = [];
process.stdin.resume();
process.stdin.setEncoding('utf8');
process.stdin.on('data', c => chunks.push(c));
process.stdin.on('end', () => {
  const input = chunks.join('');
  const result = spawnSync(process.execPath, [${escaped}], {
    input,
    encoding: 'utf8',
    timeout: 30000,
    maxBuffer: 10 * 1024 * 1024,
  });

  // Claude Code signals block via exit-code 2 + JSON stdout {reason?}.
  // Codex expects exit 0 + JSON stdout {permissionDecision:"deny"}.
  if (result.status === 2) {
    let reason = '';
    try { reason = JSON.parse(result.stdout || '{}').reason || ''; } catch {}
    process.stdout.write(JSON.stringify({ permissionDecision: 'deny', reason }) + '\\n');
    process.exit(0);
  }

  if (result.status !== 0) {
    if (result.stderr) process.stderr.write(result.stderr);
    process.exit(result.status ?? 1);
  }

  if (result.stdout) {
    try {
      const out = JSON.parse(result.stdout);
      // Codex does not recognise additionalContext — strip to avoid silent failures.
      delete out.additionalContext;
      process.stdout.write(JSON.stringify(out) + '\\n');
    } catch {
      // Non-JSON stdout: forward as-is
      process.stdout.write(result.stdout);
    }
  }
});
`;
}

/**
 * Return a content-addressed filename for a wrapper script.
 * Uses the first 8 hex chars of SHA-256 of the original path so two hooks
 * with the same basename in different directories never collide.
 *
 * @param originalPath - Absolute path to the original hook script.
 * @returns e.g. "compat-a1b2c3d4-my-hook.cjs"
 */
export function wrapperFilename(originalPath: string): string {
  const hash = crypto.createHash('sha256').update(originalPath).digest('hex').slice(0, 8);
  return `compat-${hash}-${path.basename(originalPath)}`;
}

/**
 * Write Codex-compatible wrapper scripts for every plain .cjs hook in destHooksDir.
 * Skips files that are already wrappers (compat-* prefix).
 *
 * @param destHooksDir - Absolute path to the provider's hooks/ directory.
 * @returns Map of originalAbsPath → wrapperAbsPath.
 */
export function installHookWrappers(destHooksDir: string): Map<string, string> {
  const wrapperMap = new Map<string, string>();
  if (!fs.existsSync(destHooksDir)) return wrapperMap;

  for (const entry of fs.readdirSync(destHooksDir, { withFileTypes: true })) {
    if (!entry.isFile()) continue;
    if (!entry.name.endsWith('.cjs')) continue;
    if (entry.name.startsWith('compat-')) continue; // never wrap a wrapper

    const originalPath = path.join(destHooksDir, entry.name);
    const wrapperName = wrapperFilename(originalPath);
    const wrapperPath = path.join(destHooksDir, wrapperName);

    fs.writeFileSync(wrapperPath, generateHookWrapper(originalPath), 'utf8');
    wrapperMap.set(originalPath, wrapperPath);
  }
  return wrapperMap;
}

/**
 * Build the hooks.json array for Codex, translating settings.json hook config.
 * Only includes Codex-supported events; command paths are rewritten to the
 * corresponding wrapper script so protocol translation happens at runtime.
 *
 * @param allHooks    - settings.json `hooks` section (unknown shape at boundary).
 * @param destHooksDir - Absolute path to ~/.codex/hooks/.
 * @param wrapperMap  - originalPath → wrapperPath from installHookWrappers().
 */
export function buildCodexHooksJson(
  allHooks: unknown,
  destHooksDir: string,
  wrapperMap: Map<string, string>,
): CodexHookEntry[] {
  const entries: CodexHookEntry[] = [];
  if (typeof allHooks !== 'object' || allHooks === null) return entries;

  for (const [event, groups] of Object.entries(allHooks as Record<string, unknown>)) {
    if (!CODEX_SUPPORTED_EVENTS.has(event)) continue;

    for (const group of (Array.isArray(groups) ? groups : [])) {
      if (typeof group !== 'object' || group === null) continue;
      const g = group as Record<string, unknown>;
      const hookList = Array.isArray(g.hooks) ? g.hooks : [];

      for (const hook of hookList) {
        if (typeof hook !== 'object' || hook === null) continue;
        const h = hook as Record<string, unknown>;
        if (h.type !== 'command' || typeof h.command !== 'string') continue;

        const m = h.command.match(/node\s+\.claude\/hooks\/(.+\.cjs)/);
        if (!m) continue;

        const origScript = path.join(destHooksDir, m[1]);
        // Prefer the wrapper; fall back to original if wrapper wasn't generated.
        const useScript = wrapperMap.get(origScript) ?? origScript;
        const absScript = useScript.replace(/\\/g, '/');

        const entry: CodexHookEntry = {
          event,
          command: { script: `node "${absScript}"` },
        };
        if (typeof g.matcher === 'string') entry.matcher = g.matcher;
        if (typeof h.timeout === 'number') entry.command.timeout_sec = h.timeout;

        entries.push(entry);
      }
    }
  }
  return entries;
}

/**
 * Enable the hooks feature flag in ~/.codex/config.toml.
 * Required by Codex CLI before it processes hooks.json.
 *
 * Strategy (idempotent):
 *   1. If already managed (sentinel present) — no-op
 *   2. If [features] section exists — inject `hooks = true` after it
 *   3. Otherwise — append a HailyKit-managed block
 *
 * @param providerDir - Absolute path to ~/.codex/.
 */
export function writeCodexConfigToml(providerDir: string): void {
  const configPath = path.join(providerDir, 'config.toml');
  const SENTINEL = '# --- hailykit-hooks-start ---';
  const SENTINEL_END = '# --- hailykit-hooks-end ---';

  let content = '';
  if (fs.existsSync(configPath)) {
    content = fs.readFileSync(configPath, 'utf8');
    if (content.includes(SENTINEL)) return; // already present

    if (content.includes('[features]')) {
      // Inject into existing section — avoid duplicate key if hooks already there.
      if (!content.includes('hooks = true')) {
        content = content.replace(
          /\[features\]/,
          '[features]\nhooks = true  # added by hailykit',
        );
        fs.writeFileSync(configPath, content, 'utf8');
      }
      return;
    }
  }

  const block = `\n${SENTINEL}\n[features]\nhooks = true\n${SENTINEL_END}\n`;
  fs.mkdirSync(providerDir, { recursive: true });
  fs.writeFileSync(configPath, content + block, 'utf8');
}
